Repository NBcamp-Android-Final-Project/Nbcamp_final_account_book, pull requests merged in 2023-10, with the labels that each got.

#8 HomeFragment 달력
  app/src/main/java/com/nbcam_final_account_book/persentation/home/CalendarAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/res/drawable/circle_stroke_mix.xml
  app/src/main/res/drawable/ic_calendar_selected_arrow_left.xml
  app/src/main/res/drawable/ic_calendar_selected_arrow_right.xml
  app/src/main/res/drawable/ic_calendar_selector_arrow_left.xml
  app/src/main/res/drawable/ic_calendar_selector_arrow_right.xml
  app/src/main/res/drawable/ic_calendar_unselected_arrow_left.xml
  app/src/main/res/drawable/ic_calendar_unselected_arrow_right.xml
  app/src/main/res/layout/calendar_item_day.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/values/colors.xml
Labels: feature, design, docs

#13 MoreFragment UI
  app/src/main/res/drawable/bg_more_btn.xml
  app/src/main/res/drawable/ic_backup.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_tag.xml
  app/src/main/res/drawable/ic_template.xml
  app/src/main/res/layout/more_fragment.xml
Labels: design

#14 상시 로그인 및 로그아웃 버튼 추가
  app/build.gradle
  app/src/main/java/com/nbcam_final_account_book/data/sharedprovider/SharedProvider.kt
  app/src/main/java/com/nbcam_final_account_book/data/sharedprovider/SharedProviderImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/login/LoginActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/login/LoginViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/strings.xml
Labels: feature

#16 모델 변경,상수 추가,더미 데이터 변경
  app/src/main/java/com/nbcam_final_account_book/data/model/DummyData.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/remote/ResponseEntryModel.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/login/LoginViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
Labels: feature

#17 LockActivity, LockSettingFragment UI 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/res/drawable/ic_backspace.xml
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_line.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/layout/lock_activity.xml
  app/src/main/res/layout/lock_setting_fragment.xml
  app/src/main/res/layout/number_pad.xml
Labels: feature, design

#21 LockSettingFragment 기능
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingViewModel.kt
Labels: fix

#23 HomeFragment에 바텀시트 구현 / 메인달력에 DatePicker 연결
  app/src/main/java/com/nbcam_final_account_book/data/model/DummyData.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/EntryAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/SpinnerDatePickerDialog.kt
  app/src/main/res/layout/home_bottom_sheet.xml
  app/src/main/res/layout/home_bottom_sheet_item.xml
  app/src/main/res/layout/home_fragment.xml
Labels: feature, design

#29 테스트 코드 주석처리!
  app/src/main/java/com/nbcam_final_account_book/persentation/login/LoginActivity.kt
Labels: !hotfix

#31 LockSettingFragment 뒤로가기 에러 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockActivity.kt
  app/src/main/res/layout/lock_activity.xml
Labels: fix

#32 더미데이터 추가
  app/src/main/java/com/nbcam_final_account_book/data/model/DummyData.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/login/LoginViewModel.kt
Labels: feature

#34 LockActivity, LockSettingFragment 파일명 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockSettingActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/res/layout/lock_setting_activity.xml
  app/src/main/res/layout/number_pad.xml
  app/src/main/res/layout/pin_fragment.xml
Labels: refactor, rename

#38 LockSettingActivity를 Fragment로 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockSettingActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/res/layout/lock_activity.xml
  app/src/main/res/layout/lock_setting_fragment.xml
  app/src/main/res/navigation/nav_lock.xml
Labels: feature, fix, refactor

#42 Feature/entry remodeling
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/ModalBottomFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagRecyclerAdapter.kt
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/activity_entry.xml
  app/src/main/res/layout/fragment_modal_bottom.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: design

#43 병합충돌 해결
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TemplateDataEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/AndroidRoomDataBase.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TemplateDataDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryViewModel.kt
Labels: !hotfix

#44 [DESIGN]바텀시트 UI 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/layout/home_bottom_sheet.xml
  app/src/main/res/layout/tag_fragment.xml
  app/src/main/res/values/styles.xml
Labels: fix, design

#46 스플래쉬 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/FirstActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/LoginViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/splash/SplashFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/TemplateViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addtemplate/TemplateAddFragment.kt
  app/src/main/res/layout/first_activity.xml
  app/src/main/res/layout/first_login_fragment.xml
  app/src/main/res/layout/first_splash_fragment.xml
  app/src/main/res/navigation/nav_first_graph.xml
Labels: feature

#47 [DESIGN]바텀시트 / 홈프레그 먼트 UI 수정
  app/src/main/res/drawable/home_bottom_checked_btn.xml
  app/src/main/res/drawable/home_bottom_selector_pay_btn.xml
  app/src/main/res/drawable/home_bottom_text_selector.xml
  app/src/main/res/drawable/home_bottom_unchecked_btn.xml
  app/src/main/res/drawable/ic_bottom_sheet_add.xml
  app/src/main/res/layout/home_bottom_sheet.xml
  app/src/main/res/layout/home_fragment.xml
Labels: design

#49 ModalBottomFragment 상단에 날짜 및 Tag ListAdapter 구현
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/ModalBottomFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/ModalTagListAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagRecyclerAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagViewModel.kt
  app/src/main/res/drawable/shape_oval.xml
  app/src/main/res/layout/activity_entry.xml
  app/src/main/res/layout/fragment_modal_bottom.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_tag.xml
  app/src/main/res/layout/tag_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#50 [FEATURE]getBudget 추가
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
Labels: feature

#51 더미 데이터 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/data/model/DummyData.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/local/DataEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TemplateEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/AndroidRoomDataBase.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TemplateDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/FirstActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/splash/SplashFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewPagerAdapter.kt
  app/src/main/res/layout/template_budget_fragment.xml
Labels: feature

#54 비밀번호 변경, 비밀번호 설정 여부
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/LockSharedViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/locksetting/LockSettingViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinViewModel.kt
  app/src/main/res/layout/lock_setting_fragment.xml
Labels: feature, fix

#57 Entry-room추가
  app/src/main/java/com/nbcam_final_account_book/data/model/local/EntryEntitiy.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/AndroidRoomDataBase.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/EntryDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/budget/BudgetModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryDetailFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/ModalBottomFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/ViewPagerAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagListAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
  app/src/main/res/drawable/ic_modify.xml
  app/src/main/res/layout/activity_entry.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/fragment_entry_detail.xml
  app/src/main/res/layout/item_tag.xml
  app/src/main/res/layout/tag_fragment.xml
  app/src/main/res/navigation/nav_entry_graph.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/themes.xml
Labels: feature

#58 room database table 추가
  app/src/main/java/com/nbcam_final_account_book/data/model/local/BudgetEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/local/EntryEntitiy.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TagEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/AndroidRoomDataBase.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/BudgetDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/EntryDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TagDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TemplateDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/ReturnSettingModel.kt
Labels: feature

#59 [FEATURE] Chart 만들기
  app/build.gradle
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/res/layout/chart_fragment.xml
Labels: feature, design

#62 더미데이터 삽입 및 다중 템플릿 베이스 구축
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TagEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/BudgetDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/EntryDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TagDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryDetailFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
Labels: feature

#65 테스트 코드 작성
  app/src/main/java/com/nbcam_final_account_book/data/model/remote/ResponseEntryModel.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/remote/ResponseTagModel.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/BudgetDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/EntryDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TagDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagModel.kt
Labels: feature

#66 Entry 액티비티 수정, 달력 추가
  app/build.gradle
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryDetailFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/res/drawable/selector_tablayout.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/fragment_entry_detail.xml
  app/src/main/res/navigation/nav_entry_graph.xml
  gradle.properties
Labels: feature, design

#68 삽입 로직 변경 및 테스트 코드 삽입
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
Labels: feature

#71 data class변경에 따른 room database 버전 업
  app/src/main/java/com/nbcam_final_account_book/data/model/local/BudgetEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/local/EntryEntitiy.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/AndroidRoomDataBase.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
Labels: feature

#72 백업 베이스 구축 및 테스트 코트 삽입
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/BudgetDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/EntryDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TagDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TemplateDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
Labels: feature

#74 MyPage UI 구성
  app/build.gradle
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/AccountBookAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/SharedUserAdapter.kt
  app/src/main/res/color/mypage_text_color_active.xml
  app/src/main/res/layout/account_book_item.xml
  app/src/main/res/layout/more_fragment.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/shared_user_item.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature, design

#76 More, MyPage 리팩토링
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/more/MoreFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/AccountBookAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/SharedUserAdapter.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/ic_tag.xml
  app/src/main/res/layout/more_fragment.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: fix, design

#78 데이터 동기화
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TemplateDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
Labels: feature

#79 [FEATURE]ChartFragment Tab UI
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/res/drawable/chart_radio_button_day_checked.xml
  app/src/main/res/drawable/chart_radio_button_day_selector.xml
  app/src/main/res/drawable/chart_radio_button_day_unchecked.xml
  app/src/main/res/drawable/chart_radio_button_month_checked.xml
  app/src/main/res/drawable/chart_radio_button_month_selector.xml
  app/src/main/res/drawable/chart_radio_button_month_unchecked.xml
  app/src/main/res/drawable/chart_radio_button_period_checked.xml
  app/src/main/res/drawable/chart_radio_button_period_selector.xml
  app/src/main/res/drawable/chart_radio_button_period_unchecked.xml
  app/src/main/res/drawable/chart_radio_button_week_checked.xml
  app/src/main/res/drawable/chart_radio_button_week_selector.xml
  app/src/main/res/drawable/chart_radio_button_week_unchecked.xml
  app/src/main/res/drawable/chart_tab_list_perc_text_border.xml
  app/src/main/res/drawable/icon_tag_traffic.xml
  app/src/main/res/layout/chart_fragment.xml
  app/src/main/res/layout/chart_tab_list_item.xml
  app/src/main/res/values/colors.xml
Labels: design

#80 [FEATURE] DummyData -> Room
  app/src/main/java/com/nbcam_final_account_book/persentation/home/EntryAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
Labels: feature

#81 주석 추가
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
Labels: feature

#82 Feature/entry final
  app/build.gradle
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryDetailFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/fragment_entry_detail.xml
  app/src/main/res/layout/item_tag.xml
  app/src/main/res/values/themes.xml
  gradle.properties
Labels: fix

#87 구글 로그인 디버깅 픽스
  app/google-services.json
  app/src/main/res/layout/first_splash_fragment.xml
Labels: fix

#88 MyPage 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/SharedUsersAdapter.kt
  app/src/main/res/drawable/bg_mypage_profile.xml
  app/src/main/res/drawable/ic_bin.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_mypage_profile.xml
  app/src/main/res/drawable/my_page_switch_thumb.xml
  app/src/main/res/drawable/my_page_switch_track.xml
  app/src/main/res/layout/my_page_edit_name_dialog.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/my_page_gallery_bottom_sheet.xml
  app/src/main/res/layout/my_page_shared_user_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_lock.xml
  app/src/main/res/values/colors.xml
Labels: feature

#89 build.gradle 오류 수정
  app/build.gradle
Labels: !hotfix

#90 홈 프래그먼트 income pay 연결
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/home_fragment.xml
Labels: feature

#91 라이브 데이터 연결 완
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
Labels: feature

#92 entry 데이트 피커 날짜 편집
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
Labels: feature

#95 MyPage UI 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_backup.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/ic_sync.xml
  app/src/main/res/drawable/ic_tag.xml
  app/src/main/res/drawable/ic_template.xml
  app/src/main/res/drawable/my_page_switch_track.xml
  app/src/main/res/layout/my_page_fragment.xml
Labels: fix, design

#100 MyPage 데이터 연결
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/ItemSpacingDecoration.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/my_page_shared_user_item.xml
Labels: feature, fix

#102 동기화 구현
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/LoginViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/splash/SplashFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
Labels: feature

#103 [FEATURE] Entry UI
  app/src/main/res/drawable/entry_btn_border.xml
  app/src/main/res/drawable/selector_tablayout.xml
  app/src/main/res/drawable/tag_item_border.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/item_tag.xml
Labels: design

#104 [FEATURE] Color값 수정
  app/src/main/res/layout/fragment_entry.xml
Labels: design

#105 Feature/tag dialog
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/DialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/edit/EditTagFragment.kt
  app/src/main/res/drawable/alert_white_border.xml
  app/src/main/res/layout/edit_tag_fragment.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#106 카테고리 아이템 리스트
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/res/drawable/ic_money.xml
Labels: fix

#108 마이페이지 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/res/color/mypage_text_color_active.xml
  app/src/main/res/drawable/bg_mypage_profile_item.xml
  app/src/main/res/layout/my_page_fragment.xml
Labels: fix, design

#109 Feature/tag dialog
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/TagListAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/DialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/tag_fragment.xml
Labels: feature

#110 TagFragment 삭제 다이얼로그 구현
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/DialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
Labels: feature

#116 회원가입 UI
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/first_login_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
Labels: feature, design

#119 edit연결 및 room database 구조 변경
  app/src/main/java/com/nbcam_final_account_book/data/model/local/DeleteEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TagEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/AndroidRoomDataBase.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DeleteDao.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/TagDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/dialog/template/TemplateDialogViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/DialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/ItemTouchHelperCallback.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
Labels: feature

#122 Toolbar 관련 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/res/layout/main_activity.xml
Labels: fix, design

#123 툴바 가계부 이름 표시 및 템플릿 다이얼로그
  app/src/main/java/com/nbcam_final_account_book/persentation/dialog/template/TemplateDialogAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/dialog/template/TemplateDialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/dialog/template/TemplateDialogViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/res/layout/main_activity.xml
Labels: feature, design

#125 [FEATURE] Chart Room이랑 연동
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartTagModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/res/values/colors.xml
Labels: feature, design

#126 동기화 버튼 오류 수정
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DeleteDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/dialog/template/TemplateDialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/splash/SplashFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/TemplateActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/TemplateType.kt
Labels: !hotfix

#129 EditTagFragment -> 태그 삭제/추가 room 연결
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TagEntity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/DialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/edit/EditTagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/edit/EditTagViewModel.kt
  app/src/main/res/drawable/shape_round.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#131 [FEATURE] 차트 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
Labels: feature, design

#132 사용자 프로필 UI 수정
  app/src/main/res/drawable/bg_mypage_profile_item.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/my_page_shared_user_item.xml
Labels: fix, design

#133 백업 데이터 구조 변경
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/TemplateActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/TemplateViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addtemplate/TemplateAddFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
  app/src/main/res/drawable/ic_toolbar_list.xml
  app/src/main/res/layout/first_sign_up_fragment.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/navigation/nav_first_graph.xml
Labels: feature, fix
