Repository NBcamp-Android-Final-Project/Nbcamp_final_account_book, pull requests merged in 2023-11, with the labels that each got.

#134 회원 가입 기능 완성
  app/src/main/java/com/nbcam_final_account_book/data/model/local/TagEntity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/edit/EditTagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetFragment.kt
  app/src/main/res/layout/first_login_fragment.xml
  app/src/main/res/layout/first_sign_up_fragment.xml
  app/src/main/res/layout/template_add_fragment.xml
  app/src/main/res/layout/template_budget_fragment.xml
Labels: feature, design

#135 Feature/entry bottom category
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryModalFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/res/layout/activity_entry.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/fragment_entry_modal.xml
  app/src/main/res/layout/item_tag.xml
  app/src/main/res/navigation/nav_entry_graph.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature, design

#136 [FEATURE] ChartFragment 하단
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartListAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
Labels: feature

#139 스코프 awit적용
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/DataDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/res/layout/first_sign_up_fragment.xml
Labels: !hotfix

#144 MyPage 설정 추가
  app/src/main/res/layout/my_page_fragment.xml
Labels: design

#146 [FEATURE] 스플래쉬 화면 변경
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/FirstActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/splash/SplashFragment.kt
  app/src/main/res/anim/splash_effect.xml
  app/src/main/res/drawable/splash_bg.jpg
  app/src/main/res/drawable/splash_coin_01.png
  app/src/main/res/drawable/splash_coin_02.png
  app/src/main/res/drawable/splash_coin_03.png
  app/src/main/res/drawable/splash_coin_bg.png
  app/src/main/res/drawable/splash_coin_logo.png
  app/src/main/res/layout/first_splash_fragment.xml
Labels: feature

#148 Login, Signup 비밀번호 토글
  app/src/main/res/layout/first_login_fragment.xml
  app/src/main/res/layout/first_sign_up_fragment.xml
Labels: feature, design

#149 [FEATURE] ChartFragment
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
Labels: feature

#153 차트 애니메이션 실행
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
Labels: !hotfix

#154 Feature/withdraw account
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryModalFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/FirstActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/splash/SplashFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
  app/src/main/res/drawable/ic_shopping_cart.xml
  app/src/main/res/drawable/selector_tablayout.xml
  app/src/main/res/drawable/tag_item_border.xml
  app/src/main/res/drawable/template_item_border.xml
  app/src/main/res/layout/edit_tag_fragment.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/fragment_entry_modal.xml
  app/src/main/res/layout/template_select_dialog.xml
  app/src/main/res/layout/template_select_item.xml
Labels: feature, design

#156 회원가입, 로그인 UI
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
  app/src/main/res/color/textfield_outline_color.xml
  app/src/main/res/drawable/bg_login_btn.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_google.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/layout/first_login_fragment.xml
  app/src/main/res/layout/first_sign_up_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, fix, design

#158 SignUp TextWatcher 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
Labels: fix

#159 [FEATURE] 테마 색상 변경으로 인한 전체 색 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
  app/src/main/res/drawable/chart_radio_button_day_checked.xml
  app/src/main/res/drawable/chart_radio_button_day_unchecked.xml
  app/src/main/res/drawable/chart_radio_button_month_checked.xml
  app/src/main/res/drawable/chart_radio_button_month_unchecked.xml
  app/src/main/res/drawable/chart_radio_button_period_checked.xml
  app/src/main/res/drawable/chart_radio_button_period_unchecked.xml
  app/src/main/res/drawable/chart_radio_button_week_checked.xml
  app/src/main/res/drawable/chart_radio_button_week_unchecked.xml
  app/src/main/res/drawable/circle_stroke_mix.xml
  app/src/main/res/drawable/home_budget_layout_border.xml
  app/src/main/res/drawable/home_income_layout_border.xml
  app/src/main/res/drawable/ic_calendar_unselected_arrow_left.xml
  app/src/main/res/drawable/ic_calendar_unselected_arrow_right.xml
  app/src/main/res/layout/calendar_item_day.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: design

#161 Main, MyPage UI 및 기능
  app/src/main/java/com/nbcam_final_account_book/persentation/lock/pin/PinFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/bg_more_btn.xml
  app/src/main/res/drawable/bg_mypage_profile.xml
  app/src/main/res/drawable/bg_mypage_profile_item.xml
  app/src/main/res/drawable/ic_backspace_normal.xml
  app/src/main/res/drawable/ic_backspace_pressed.xml
  app/src/main/res/drawable/ic_circle_active.xml
  app/src/main/res/drawable/ic_circle_inactive.xml
  app/src/main/res/drawable/ic_line.xml
  app/src/main/res/drawable/my_page_switch_track.xml
  app/src/main/res/drawable/number_pad_backspace_color.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/lock_activity.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/my_page_gallery_bottom_sheet.xml
  app/src/main/res/layout/number_pad.xml
  app/src/main/res/layout/pin_fragment.xml
  app/src/main/res/navigation/nav_lock.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feature, fix, design

#163 EntryFragment 레이아웃 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
  app/src/main/res/drawable/ic_calendar_unselected_arrow_left.xml
  app/src/main/res/drawable/selector_tablayout.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/fragment_entry_modal.xml
  app/src/main/res/layout/template_select_dialog.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: design

#164 [FEATURE] 데이터 없을시 문구 표시
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
Labels: feature, design

#165 [DOCS] 아이콘 업로드
  app/src/main/res/drawable/dutoom_b.xml
  app/src/main/res/drawable/dutoom_w.xml
Labels: design, docs

#166 다크테마 레이아웃 설정
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
  app/src/main/res/drawable/recyclerview_divider.xml
  app/src/main/res/layout/edit_tag_fragment.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/tag_fragment.xml
  app/src/main/res/layout/template_select_dialog.xml
  app/src/main/res/layout/template_select_item.xml
  app/src/main/res/values/styles.xml
Labels: feature, design

#168 비밀번호 재설정 기능 구현
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
Labels: feature

#172 MyPage PR 오류 해결
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
Labels: !hotfix

#174 MyPage 비밀번호 변경 다이얼로그
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageChangePasswordDialog.kt
  app/src/main/res/layout/my_page_change_password_dialog.xml
Labels: feature, design, refactor

#176 Chat 제거
  app/src/main/java/com/nbcam_final_account_book/persentation/chat/ChatFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chat/ChatViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/res/layout/chat_fragment.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: rename

#178 [FEATURE] 가계부 이름 입력 화면 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addtemplate/TemplateAddFragment.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/template_add_fragment.xml
  app/src/main/res/values/colors.xml
Labels: feature, design

#179 [FEATURE] 예산 입력 화면 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/template/addbudget/TemplateBudgetFragment.kt
  app/src/main/res/layout/template_add_fragment.xml
  app/src/main/res/layout/template_budget_fragment.xml
Labels: feature, design

#185 [FEATURE] 홈화면, 바텀시트 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/home/EntryAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/drawable/shape_bottom_sheet.xml
  app/src/main/res/layout/home_bottom_sheet.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/template_add_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature, design

#186 [FEATURE] statusBarColor 값 적용
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/FirstActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/template/TemplateActivity.kt
  app/src/main/res/values/themes.xml
Labels: feature, design

#191 MyPage 시간 포맷 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
Labels: fix

#194 [FEATURE] chart 버그수정 feat.김명환튜터님
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartFragment.kt
Labels: fix

#196 MyPage 다듬기
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageLogoutDialog.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageWithdrawDialog.kt
  app/src/main/res/layout/template_select_item.xml
Labels: fix, design

#198 fragment_entry.xml -> tablet 에서 tablayout width 가 짧은 이슈 해결
  app/src/main/res/layout/fragment_entry.xml
Labels: fix

#199 [DESIGN] 색상 변경
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
  app/src/main/res/layout/first_splash_fragment.xml
Labels: design

#201 [DESIGN]템플릿 선택 화면 디바이더 색상 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
Labels: design

#202 앱 아이콘, 이름 설정
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: design

#203 [FEATURE] 인트로 / 홈 바텀시트 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/res/layout/template_add_fragment.xml
  app/src/main/res/layout/template_budget_fragment.xml
Labels: feature, design

#204 [DESIGN] 잔잔바리수정
  app/src/main/res/layout/chart_tab_list_item.xml
  app/src/main/res/layout/home_bottom_sheet.xml
Labels: design

#205 Release 버전의 Proguard 난독화 설정
  app/build.gradle
Labels: pack

#208 MyPage UI 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/my_page_gallery_bottom_sheet.xml
  app/src/main/res/values/dimens.xml
Labels: design

#209 fatal 오류 fix 1
  app/google-services.json
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/res/layout/home_fragment.xml
Labels: feature

#210 fatal 오류 fix 1
  app/google-services.json
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/res/layout/home_fragment.xml
Labels: feature

#212 SignUpFragment.kt:129 -> action 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/signup/SignUpFragment.kt
Labels: fix

#215 태그 관리 좌측 imageView 삭제 및 휴지통, 메뉴 아이콘 색상 변경
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/number_pad_backspace_color.xml
  app/src/main/res/layout/edit_tag_fragment.xml
  app/src/main/res/layout/item_tag_manage.xml
Labels: design

#216 검색 추가
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/firstpage/login/LoginViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
Labels: feature

#217 MyPage, SharedTemplate UI 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/shared_item.xml
  app/src/main/res/layout/shared_template_fragment.xml
Labels: fix, design

#219 dev release sync
  app/build.gradle
  app/proguard-rules.pro
Labels: !hotfix

#220 태그 관리 좌측 imageView 삭제 및 휴지통, 메뉴 아이콘 색상 변경
  app/src/main/java/com/nbcam_final_account_book/persentation/tag/TagManageAdapter.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/layout/edit_tag_fragment.xml
  app/src/main/res/layout/item_tag_manage.xml
Labels: design

#223 난독화 범위 수정
  app/proguard-rules.pro
Labels: fix

#225 build.gradle 수정
  app/build.gradle
Labels: !hotfix

#227 회원 탈퇴 시 Firebase RTDB 데이터까지 삭제
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
Labels: feature

#228 [FEATURE] 유저 검색 기능
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/UserListAdapter.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/shared_item.xml
  app/src/main/res/layout/shared_template_fragment.xml
Labels: feature, design

#232 [FEATURE] 최대 글자수 제거
  app/src/main/res/layout/shared_template_fragment.xml
Labels: feature

#233 MyPage 사용자 데이터 DB 연결
  app/src/main/java/com/nbcam_final_account_book/data/model/local/UserDataEntity.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
Labels: feature, fix

#235 Authentication 및 Firestore 데이터 삭제 동작 안함 해결
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
Labels: fix

#236 [FEATURE] coil 추가
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/UserListAdapter.kt
Labels: feature

#238 [FEATURE]아이템클릭시 다이얼로그
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedPostDialog.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/UserListAdapter.kt
  app/src/main/res/layout/dialog_shared_post.xml
Labels: feature, design

#240 공유 알림 화면 UI
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/dialog/SharedRequestDialogFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/notification/SharedNotificationAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/notification/SharedNotificationFragment.kt
  app/src/main/res/drawable/default_profile.xml
  app/src/main/res/drawable/ic_notifications.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/shared_notification_fragment.xml
  app/src/main/res/layout/shared_notification_item.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: design

#241 [FEATURE] 공유하기 기능 추가
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedPostDialog.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/unit/Unit.kt
Labels: feature

#242 [FEATURE] 수입 지출에 따른 링표시 변경
  app/src/main/java/com/nbcam_final_account_book/persentation/home/CalendarAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeViewModel.kt
  app/src/main/res/drawable/circle_stroke_expend.xml
  app/src/main/res/drawable/circle_stroke_income.xml
Labels: feature, design

#243 Shared Template 기능 구현 중
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/notification/SharedNotificationFragment.kt
  app/src/main/res/layout/fragment_dialog.xml
Labels: feature

#245 [FEATURE] 수입,지출 수정 가능
  app/src/main/java/com/nbcam_final_account_book/data/model/local/EntryEntitiy.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryActivity.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/entry/EntryViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/EntryAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/res/layout/fragment_entry.xml
Labels: feature

#246 [DESIGN] 차트 색상 변경
  app/src/main/java/com/nbcam_final_account_book/persentation/chart/ChartViewModel.kt
Labels: design

#247 [FIX] 다이얼로그 가운데정렬
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedPostDialog.kt
Labels: fix

#250 가계부 공유 오류 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/shared/SharedTemplateViewModel.kt
Labels: fix

#252 비밀번호 변경 다이얼로그 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageChangePasswordDialog.kt
  app/src/main/res/color/btn_text_color.xml
  app/src/main/res/layout/my_page_change_password_dialog.xml
Labels: fix, design, refactor

#254 사용자 이름 수정 관련 코드 수정
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageChangePasswordDialog.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageEditNameDialog.kt
  app/src/main/java/com/nbcam_final_account_book/util/ContextUtil.kt
  app/src/main/res/layout/my_page_edit_name_dialog.xml
Labels: fix, design, refactor

#258 [FEAT] 삭제 로직 구현
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/room/RoomRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/data/room/dao/EntryDao.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/EntryAdapter.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/main/MainViewModel.kt
  app/src/main/res/layout/dialog_delete_entry.xml
  app/src/main/res/layout/home_bottom_sheet_item.xml
Labels: feature, design

#259 계정삭제 다이얼로그 수정
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepository.kt
  app/src/main/java/com/nbcam_final_account_book/data/repository/firebase/FireBaseRepositoryImpl.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageWithdrawDialog.kt
  app/src/main/res/layout/my_page_withdraw_dialog.xml
Labels: feature, design, refactor

#261 Logout Dialog, MyPage ProfileImage
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/mypagedialog/MyPageLogoutDialog.kt
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/my_page_logout_dialog.xml
  app/src/main/res/values/styles.xml
Labels: fix, design, refactor

#263 구글플레이스토어 업데이트 전 수정
  app/build.gradle
  app/src/main/java/com/nbcam_final_account_book/persentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/my_page_fragment.xml
Labels: fix, docs

#265 가계부 관리 다이얼로그, 태그 관리
  app/src/main/java/com/nbcam_final_account_book/persentation/template/dialog/template/TemplateDialogFragment.kt
  app/src/main/res/layout/edit_tag_fragment.xml
  app/src/main/res/layout/fragment_entry.xml
  app/src/main/res/layout/template_select_dialog.xml
Labels: fix, design
